version: '3.3'
networks:
  jina-network:
    driver: bridge
services:
  encoder-head:
    image: jinaai/jina:master-py38-perf
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - encoder/head
    - --polling
    - ANY
    - --port-in
    - '8081'
    - --runtime-cls
    - HeadRuntime
    - --pod-role
    - HEAD
    - --connection-list
    - '{"0": ["encoder-rep-0:8081", "encoder-rep-1:8081"]}'
    - --uses-metas
    - '{}'
    - --native
    networks:
    - jina-network
  encoder-rep-0:
    image: jinahub/0hnlmu3q:62156784abe7c5954d17631e
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - encoder/rep-0
    - --uses
    - config.yml
    - --port-in
    - '8081'
    - --replicas
    - '2'
    - --uses-metas
    - '{}'
    - --native
    networks:
    - jina-network
  encoder-rep-1:
    image: jinahub/0hnlmu3q:62156784abe7c5954d17631e
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - encoder/rep-1
    - --uses
    - config.yml
    - --port-in
    - '8081'
    - --replicas
    - '2'
    - --uses-metas
    - '{}'
    - --native
    networks:
    - jina-network
  indexer-head:
    image: jinaai/jina:3.0.2-py38-perf
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - indexer/head
    - --port-in
    - '8081'
    - --runtime-cls
    - HeadRuntime
    - --pod-role
    - HEAD
    - --shards
    - '2'
    - --connection-list
    - '{"0": ["indexer-0:8081"], "1": ["indexer-1:8081"]}'
    - --uses-metas
    - '{}'
    - --native
    networks:
    - jina-network
  indexer-0:
    image: jinahub/pn1qofsj:621567a5dbd7cde99b1bc0f7
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - indexer-0
    - --uses
    - config.yml
    - --port-in
    - '8081'
    - --shards
    - '2'
    - --uses-metas
    - '{}'
    - --uses-with
    - '{"dim": 512}'
    - --native
    networks:
    - jina-network
  indexer-1:
    image: jinahub/pn1qofsj:621567a5dbd7cde99b1bc0f7
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - indexer-1
    - --uses
    - config.yml
    - --port-in
    - '8081'
    - --shard-id
    - '1'
    - --shards
    - '2'
    - --uses-metas
    - '{}'
    - --uses-with
    - '{"dim": 512}'
    - --native
    networks:
    - jina-network
  gateway:
    image: jinaai/jina:3.0.2-py38-standard
    entrypoint:
    - jina
    command:
    - gateway
    - --polling
    - ANY
    - --port-in
    - '56474'
    - --expose-endpoints
    - '{}'
    - --protocol
    - HTTP
    - --port-expose
    - '8080'
    - --graph-description
    - '{"encoder": ["indexer"], "start-gateway": ["encoder"], "indexer": ["end-gateway"]}'
    - --deployments-addresses
    - '{"encoder": ["encoder-head:8081"], "indexer": ["indexer-head:8081"]}'
    - --pod-role
    - GATEWAY
    expose:
    - '8080'
    - '56474'
    ports:
    - 8080:8080
    - 56474:56474
    networks:
    - jina-network
